# Generated by Django 4.1.5 on 2023-02-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pedido_pizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='tamanho',
            field=models.CharField(choices=[('Brotinho', 'Brotinho'), ('Media', 'Media'), ('Familia', 'Familia'), ('Gigante', 'Gigante')], max_length=200, null=True),
        ),
    ]
