# Generated by Django 4.1.5 on 2023-02-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_pedido_cliente_pedido_pizza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='pizza',
        ),
        migrations.AddField(
            model_name='pedido',
            name='pizza',
            field=models.ManyToManyField(to='accounts.pizza'),
        ),
    ]
